import type { Metadata } from "next";
import { Inter, Spectral } from "next/font/google";

import "./globals.css";
import { cn } from "@/lib/utils";
import StoreProvider from "@/providers/provider/store-provider";

const fontSans = Inter({
  subsets: ["latin"],
});

const spectral = Spectral({
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700", "800"],
  variable: "--font-news",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background antialiased grainy font-sans",
          fontSans.className
        )}
      >
        <StoreProvider>{children}</StoreProvider>
      </body>
    </html>
  );
}
